# Generated by Django 4.1.11 on 2023-09-21 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroToken',
            fields=[
                ('RegistroTokenId', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario_comprador', models.CharField(max_length=24)),
                ('id_usuario_vendedor', models.CharField(max_length=24)),
                ('tipo_transaccion', models.CharField(max_length=100)),
                ('nombre_banco', models.CharField(max_length=100)),
                ('tipo_cuenta', models.CharField(max_length=100)),
                ('numero_cuenta', models.CharField(max_length=100)),
                ('estado_transaccion', models.BooleanField(default=False)),
                ('fecha_transaccion', models.DateTimeField(auto_now_add=True)),
                ('valor_transaccion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('TokenId', models.AutoField(primary_key=True, serialize=False)),
                ('id_usuario', models.CharField(max_length=24)),
                ('cantidad', models.CharField(max_length=24)),
                ('Tokengenerado', models.CharField(max_length=500)),
            ],
        ),
    ]
