# Generated by Django 4.1.11 on 2023-09-21 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroTienda',
            fields=[
                ('RegistroTiendaId', models.AutoField(primary_key=True, serialize=False)),
                ('id_vendedor', models.CharField(max_length=24)),
                ('id_comprador', models.CharField(max_length=24)),
                ('titulo_producto', models.CharField(max_length=24)),
                ('precio_producto', models.CharField(max_length=24)),
                ('imagen_producto', models.CharField(max_length=24)),
                ('detalle_producto', models.CharField(max_length=24)),
                ('estado_envio', models.BooleanField(default=False)),
                ('estado_recibido', models.BooleanField(default=False)),
                ('estado_pago_shopken', models.BooleanField(default=False)),
                ('RegistroTokenId', models.CharField(blank=True, max_length=24, null=True)),
            ],
        ),
    ]
